#!/usr/bin/env bash
#Installing web server

sudo apt -y update
sudo apt -y install nginx
echo "Hello world!" > /var/www/html/index.html
cat <<EOF > /etc/nginx/sites-available/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;


        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
	}
}
EOF
sudo service nginx start
